### ISSUE TITLE
how do you manage the global nixos configuration on your PC

### ISSUE THREAD

**Issue by k2s** [chris-martin/nixos-config#1]
this repo contains comment `My nix config now lives at https://github.com/chris-martin/home/tree/master/.nixpkgs`, but that file doesn't exists.

How do you manage the global nixos configuration on your PC ?

thank you

**Comment by chris-martin** [comment]
Hi, that directory just got renamed from `.nixpkgs` to `.nix`.

https://github.com/chris-martin/home/tree/master/.nix

**Comment by chris-martin** [comment]
The system NixOS config is `sys.nix` (which I run using the `nx-sys` script in that same directory)
